### ISSUE TITLE
Some Directories Have Spaces in Their Names

### ISSUE THREAD

**Issue by liam-middlebrook** [FOSSRIT/Free-Culture-Projects#4]
This should be changed to use an underscore format for ease of access in a terminal. Here's a reference article that shows why this is bad and how to change it. http://kaslnetwork.com/articles/spaces-in-file-names-or-directory-names-bad/

I also think that directory names should be all lowercase. This will also make it easier to enter directories with minimal keypresses.

**Comment by msoucy** [comment]
Pull requests welcome.

**Comment by JosephCoppola** [comment]
Can't wait for you to see my file paths hahahahaha
