### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by liam-middlebrook** [FOSSRIT/Free-Culture-Projects#5]
First, the standard disclaimer: I am not a lawyer, and this does not constitute legal or financial advice.

Generally, IMHO, it is a good idea to use FSF or OSI Approved Licenses (which can be found here https://www.gnu.org/licenses/licenses.html and here http://opensource.org/licenses/category)

The Free Software Foundation has a useful guide for choosing a license: https://www.gnu.org/licenses/license-recommendations.html

I often reference the Software Freedom Law Center's Legal Primer for both practical and academic purposes (highly recommended): https://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-60002.2

https://tldrlegal.com/ is quite a useful resource for comparing the various FOSS licenses out there once you have some context

To get ahold of actual lawyers/advisors who help FOSS projects, you can reach out to the FSF, SFLC, and OSI at:
licensing@fsf.org
help@softwarefreedom.org
license-discuss@opensource.org

Hope this helps, and happy hacking!

**Comment by msoucy** [comment]
@sctjkc01 and @brendanwhitfield , your submissions are already in so I'm singling you out.

For this class, I feel that the CC-BY-SA license makes the most sense. Thoughts?

**Comment by brendan-w** [comment]
Works for me.

**Comment by liam-middlebrook** [comment]
@msoucy looks like we're good to add the CC-BY-SA as a blanket license. If people want something else they can individually license their subfolder.
